[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shared-client"
version = "0.1.0"
description = "Shared Client SDK for StudyBuilder Data Utilities"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.20.0",
    "httpx_auth>=0.20.0"
]
